### ISSUE TITLE
[BUG] - ImageUtilities

### ISSUE THREAD

**Issue by FomalhautBravo** [mwittrien/BetterDiscordAddons#1902]
**Describe the bug**
The option "save image as..."is not working, no matter how many times I click the button, nothing happened.

**To Reproduce**
Every time when click on every "save image as..." button.

**Expected behavior**
Images to be saved, or pop up a box, at least have some reply

**Discord Build (stable, ptb or canary):**
Stable 152727 (10e8836)

**Additional context**
Restarting the plugin, Discord or adding new saving location all didn' work.

**Comment by mwittrien** [comment]
works just fine for me, check the console `ctrl + shift + i` for issues, make sure developer options are enabled in the BD settings so you can access the console

**Comment by FomalhautBravo** [comment]
![image](https://user-images.githubusercontent.com/116103073/196665373-c9498a33-da9e-427e-8624-240831b0c20f.png)
I enabled all developer options in BD settings and nothing changed, images still can't be saved, and...to be honest I didn't even know if this console really showed where the issue is

**Comment by mwittrien** [comment]
check the console while you attempt to save and image and check if a new red error pop up

**Comment by FomalhautBravo** [comment]
That's exactly the point: nothing appeared, no red error, no yellow warning, nothing

**Comment by FomalhautBravo** [comment]
Could be ,I need to use VPN for Discord to function, but it's all good when I disable the plugin(that is, I may freely save images with a dialog pop up and show me the default download location); With the plugin activated, I can still save the image by opening it on my browser, but that's not what it supposed to be:/
By the way, I'm not authorized to send messages in the Discord server (#support, or any other channel), and I can't find a way to validate my role or something like that, is it possible for me to get full access to those channels?

**Comment by mwittrien** [comment]
Hmm i might be able to do sth about it tomorrow

My Server is in lockdown till most my stuff is fixed

**Comment by FomalhautBravo** [comment]
I see, and also I've just found some tremendous bugs with this new translater plugin...I'll open a new issue about them

**Comment by mwittrien** [comment]
Redownload ImageUtilities and check if it fixes your issue with the file dialog window

**Comment by FomalhautBravo** [comment]
Will...it didn't ping me that the plugin was updated, I reinstalled the plugin anyway and the issue is still there...I give up, leave it be for me
