### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by yushehua** [mwittrien/BetterDiscordAddons#2957]
**Describe the bug**
The translation plug-in is prompted to be enabled but cannot be used.

**To Reproduce**
today

**Expected behavior**
I want to know how to solve it.

**Screenshots**

![Image](https://github.com/user-attachments/assets/4d6fb830-b3f7-4b6c-ae0c-43c5134afc6e)

![Image](https://github.com/user-attachments/assets/3806a4f7-4074-4ec1-b4db-2f3e795bf87a)

![Image](https://github.com/user-attachments/assets/25bf4aed-2a4d-4cba-a668-3995e7c184d0)

**Discord Build (stable, ptb or canary):**
stable

**Additional context**
I installed the translation plugin, but it doesn't work. There are no translation options for either the settings button in the input bar or the right mouse button.

**Comment by mwittrien** [comment]
Redownload BDFDB, delete 0BDFDB.data.json and reload discord.

The Plugin should be working fine, make sure you are right clicking a message to translate it

**Comment by yushehua** [comment]
> 重新下载 BDFDB，删除 0BDFDB.data.json 并重新加载 discord。
> 
> 该插件应该工作正常，请确保您右键单击消息以翻译它

![Image](https://github.com/user-attachments/assets/bac3b1d3-b9a2-4880-8ada-c836c9aa53a4)
I removed and reinstalled BDFDB and then removed 0BDFDB.data. JSON from the file, but when I restarted discord it reappeared, and so far the right button is still not responding.

**Comment by yushehua** [comment]
![Image](https://github.com/user-attachments/assets/8cea6c5d-aa38-470e-97ef-7167739dd26e)

**Comment by yushehua** [comment]
@mwittrien
