### ISSUE TITLE
[BUG] - MessageUtilities: Cannot set modifiers for hotkeys

### ISSUE THREAD

**Issue by FichteFoll** [mwittrien/BetterDiscordAddons#727]
**Describe the bug**
When setting a modified key as the key binding part of an action, it is saved as a different key.

May be an issue in BD itself.

**To Reproduce**
1. Try to set the key binding to just ctrl or shift.
2. Close and reopen the settings.
3. Observe that the bindings aren't working.

**Expected behavior**
The configured keybindings are saved correctly and work.

**Screenshots**

After configuring bindings:
![2021-04-05_16-53-40](https://user-images.githubusercontent.com/931051/113587727-7fff5000-962f-11eb-86ca-16ab8afb755e.png)

After reopening the settings:
![2021-04-05_16-54-09](https://user-images.githubusercontent.com/931051/113587786-92798980-962f-11eb-9812-1364d6563004.png)

**Discord Build (stable, ptb or canary):**
stable

**Additional context**
Arch Linux, German keyboard layout (tried "basic" and "neo_qwertz")

PS: How do I activate `Ctrl+T+Click`?

**Comment by mwittrien** [comment]
Should be fixed hopefully with the update for BDFDB

**Comment by mwittrien** [comment]
Ctrl+T+Click = Hold Ctrl and T and while holding down those keys press the message with the left mouse button

**Comment by FichteFoll** [comment]
I can confirm the above two eamples to show the correct keys on reloading now.

However, now 

- Ctrl T (or "LEFT CTRL + T") gets translated to "LEFT CTRL + NUMPAD 5"
- The bindings I set above in the screenshot still don't work
- The combo hints in the context menu show Mark Unread as "9+CLICK"

**Comment by Raymo111** [comment]
Can confirm this is still an issue on the latest betterdiscord (or it's resurged), @mwittrien can we get this issue reopened and the problem fixed please?
